seed: 0

data:
  path: "data"
  split: [0.7,0.5]
  batch_size: 50

model:
  input_sz: 8
  ll1: 32
  ll2: 16
  optimizer:
    lr: 3e-4

trainer:
  log_every_n_steps: 20
  max_epochs: 100
  

defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog